export const ITEM_SAVE_BEGIN   = 'ITEM_SAVE_BEGIN';
export const ITEM_SAVE_SUCCESS = 'ITEM_SAVE_SUCCESS';
export const ITEM_SAVE_FAILURE = 'ITEM_SAVE_FAILURE';

export const USER_AUTH = 'USER_AUTH';

export const NETWORK_REQUEST_BEGIN = 'NETWORK_REQUEST_BEGIN';
export const NETWORK_REQUEST_END   = 'NETWORK_REQUEST_END'; 