export const ITEM_SAVE_BEGIN   = 'ITEM_SAVE_BEGIN';
export const ITEM_SAVE_SUCCESS = 'ITEM_SAVE_SUCCESS';
export const ITEM_SAVE_FAILURE = 'ITEM_SAVE_FAILURE';

export const USER_AUTH = 'USER_AUTH';

export const NETWORK_REQUEST_BEGIN = 'NETWORK_REQUEST_BEGIN';
export const NETWORK_REQUEST_END   = 'NETWORK_REQUEST_END'; 

export const MENU_KATAGORI_BEGIN = 'MENU_KATAGORI_BEGIN';
export const MENU_KATAGORI_SUCCESS   = 'MENU_KATAGORI_SUCCESS'; 
export const MENU_KATAGORI_FAIL   = 'MENU_KATAGORI_FAIL'; 

export const FETCH_URUNLER_BEGIN    = 'FETCH_URUNLER_BEGIN';
export const FETCH_URUNLER_SUCCESS   = 'FETCH_URUNLER_SUCCESS'; 
export const FETCH_URUNLER_FAIL     = 'FETCH_URUNLER_FAIL'; 