export const ITEM_SAVE_BEGIN = "ITEM_SAVE_BEGIN";
export const ITEM_SAVE_SUCCESS = "ITEM_SAVE_SUCCESS";
export const ITEM_SAVE_FAILURE = "ITEM_SAVE_FAILURE";

export const USER_AUTH_BEGIN = "USER_AUTH_BEGIN";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAIL = "USER_AUTH_FAIL";

export const NETWORK_REQUEST_BEGIN = "NETWORK_REQUEST_BEGIN";
export const NETWORK_REQUEST_END = "NETWORK_REQUEST_END";

export const MENU_KATAGORI_BEGIN = "MENU_KATAGORI_BEGIN";
export const MENU_KATAGORI_SUCCESS = "MENU_KATAGORI_SUCCESS";
export const MENU_KATAGORI_FAIL = "MENU_KATAGORI_FAIL";

export const FETCH_URUNLER_BEGIN = "FETCH_URUNLER_BEGIN";
export const FETCH_URUNLER_SUCCESS = "FETCH_URUNLER_SUCCESS";
export const FETCH_URUNLER_FAIL = "FETCH_URUNLER_FAIL";

export const INS_MASA_BEGIN = "INS_MASA_BEGIN";
export const INS_MASA_SUCCESS = "INS_MASA_SUCCESS";
export const INS_MASA_FAIL = "INS_MASA_FAIL";
export const FETCH_MASA_BEGIN = "FETCH_MASA_BEGIN";
export const FETCH_MASA_SUCCESS = "FETCH_MASA_SUCCESS";
export const FETCH_MASA_FAIL = "FETCH_MASA_FAIL";
export const UPD_MASA_BEGIN = "UPD_MASA_BEGIN";
export const UPD_MASA_SUCCESS = "UPD_MASA_SUCCESS";
export const UPD_MASA_FAIL = "UPD_MASA_FAIL";
export const DEL_MASA_BEGIN = "DEL_MASA_BEGIN";
export const DEL_MASA_SUCCESS = "DEL_MASA_SUCCESS";
export const DEL_MASA_FAIL = "DEL_MASA_FAIL";

export const INS_BOLGE_BEGIN = "INS_BOLGE_BEGIN";
export const INS_BOLGE_SUCCESS = "INS_BOLGE_SUCCESS";
export const INS_BOLGE_FAIL = "INS_BOLGE_FAIL";
export const FETCH_BOLGE_BEGIN = "FETCH_BOLGE_BEGIN";
export const FETCH_BOLGE_SUCCESS = "FETCH_BOLGE_SUCCESS";
export const FETCH_BOLGE_FAIL = "FETCH_BOLGE_FAIL";
export const UPD_BOLGE_BEGIN = "UPD_BOLGE_BEGIN";
export const UPD_BOLGE_SUCCESS = "UPD_BOLGE_SUCCESS";
export const UPD_BOLGE_FAIL = "UPD_BOLGE_FAIL";
export const DEL_BOLGE_BEGIN = "DEL_BOLGE_BEGIN";
export const DEL_BOLGE_SUCCESS = "DEL_BOLGE_SUCCESS";
export const DEL_BOLGE_FAIL = "DEL_BOLGE_FAIL";
